//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SetupGiz.rc
//
#define IDC_ADD                         3
#define IDM_ABOUTBOX                    0x0010
#define IDM_REGISTER                    0x0020
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDR_SETUP                       101
#define IDD_SETUPGIZ_DIALOG             102
#define IDS_REGISTER                    102
#define IDS_REREGISTER                  103
#define IDS_REREGINFO1                  104
#define IDS_REREGINFO2                  105
#define IDD_PAGE_1                      107
#define IDD_PAGE_2                      108
#define IDD_FINISH                      109
#define IDD_PAGE_3                      110
#define IDD_PAGE_3A                     111
#define IDD_PAGE_4                      112
#define IDR_MAINFRAME                   128
#define IDB_PALM                        130
#define IDB_BITMAP1                     132
#define IDB_FINISH                      132
#define IDD_PAGE1_ADVANCED              134
#define IDD_NAG                         135
#define IDD_PAGE_3_CERT                 136
#define IDD_SETUP_DIALOG                502
#define IDD_PAGE_3B                     503
#define IDD_INPUT                       504
#define IDD_LICENSE                     506
#define IDC_COMPANY_NAME                1000
#define IDC_APP_NAME                    1001
#define IDC_START_MESSAGE               1002
#define IDC_SOURCE_PATH                 1003
#define IDC_BROWSE                      1004
#define IDC_DEST_LIST                   1005
#define IDC_BROWSE_DEST                 1005
#define IDC_SOURCE_LIST                 1006
#define IDC_DEST_PATH                   1006
#define IDC_GOZINTA                     1007
#define IDC_BROWSE_LICENSE              1007
#define IDC_GOZOUTA                     1008
#define IDC_LICENSE_FILE                1008
#define IDC_MOVE_UP                     1009
#define IDC_SYSTEMDIR                   1009
#define IDC_BROWSE_CERT                 1009
#define IDC_MOVE_DOWN                   1010
#define IDC_APPDIR                      1010
#define IDC_LICENSE_FILE2               1010
#define IDC_CERT_FILES                  1010
#define IDC_OTHERPATH                   1011
#define IDC_OTHERPATH_NAME              1012
#define IDC_SHARED                      1013
#define IDC_OVERWRITE                   1014
#define IDC_TEMPDIR                     1015
#define IDC_EXECUTE                     1016
#define IDC_AUTODELETE                  1017
#define IDC_OSLIST                      1018
#define IDC_SELECT_OS                   1019
#define IDC_OPTION_INSTALL              1020
#define IDC_OPTIONS                     1021
#define IDC_DESC                        1022
#define IDC_REGISTER                    1022
#define IDC_LONGDESC                    1023
#define IDC_REGISTER2                   1023
#define IDC_REG_DOT_NET                 1023
#define IDC_OPTION_LIST                 1024
#define IDC_NOEDITPATH                  1024
#define IDC_FILE_LIST                   1025
#define IDC_CDROM                       1027
#define IDC_CDROM_MULTI                 1028
#define IDC_DISKETTE                    1029
#define IDC_SELF_EXTRACT                1030
#define IDC_AUTOINSERT                  1031
#define IDC_DO_NOT_CLOSE                1032
#define IDC_ADD_NEW                     1033
#define IDC_LZCOMPRESS                  1033
#define IDC_REMOVE                      1034
#define IDC_QUIET_SETUP                 1034
#define IDC_KEY                         1035
#define IDC_DO_NOT_DEL_WORKFILES        1035
#define IDC_STRING                      1036
#define IDC_DO_NOT_DEL_WORKFILES2       1036
#define IDC_DO_NOT_REBUILD_CAB          1036
#define IDC_VALUE                       1037
#define IDC_ENTRY_LIST                  1038
#define IDC_MINI_HELP                   1039
#define IDC_REVERT                      1040
#define IDC_SAVE                        1040
#define IDC_KEY_HELP                    1041
#define IDC_NO_UNINSTALL                1041
#define IDC_ADD_STANDARD                1042
#define IDC_ADD_SHORTCUT                1042
#define IDC_IMPORT_REG                  1043
#define IDC_TEST                        1043
#define IDC_OPEN                        1044
#define IDC_ADVANCED                    1045
#define IDC_TEST2                       1046
#define IDC_TEST_LIC                    1046
#define IDC_EXEC_ARGS                   1047
#define IDC_UNINST_ARGS                 1048
#define IDC_SHOWDIRS                    1048
#define IDC_APPPATH                     1049
#define IDC_APPCOMMON                   1050
#define IDC_AUTHCODE                    1050
#define IDC_STARTMENU                   1051
#define IDC_AUTHCOMPANY                 1051
#define IDC_BOOT_AUTO                   1052
#define IDC_BOOT_ALWAYS                 1053
#define IDC_BOOT_NEVER                  1054
#define IDC_DISK1_RESERVE               1055
#define IDC_APP_LIST                    1056
#define IDC_ICON_LIST                   1058
#define IDC_FILENAME                    1059
#define IDC_ICON_FILES                  1060
#define IDC_PARMS                       1061
#define IDC_SHOWNORMAL                  1062
#define IDC_SHOWMIN                     1063
#define IDC_UPGRADE                     1063
#define IDC_SHOWMAX                     1064
#define IDC_CAPTION                     1064
#define IDC_SHOWHIDE                    1065
#define IDC_INPUT                       1065
#define IDC_CERT_LIST                   1067
#define IDC_REPOSITORY                  1068
#define IDC_COMBO1                      1069
#define IDC_WELCOME                     2000
#define IDC_LICENSE                     2001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
